# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane publish the app on TestFlight"
  lane :beta do
    increment_build_number
    build_app(scheme: "CV",
            workspace: "CV.xcworkspace",
            include_bitcode: true,  
            clean: true,
            output_directory: "./build")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :tests do
    run_tests(workspace: "CV.xcworkspace",
              devices: ["iPhone X"],
              scheme: "CV")
  end

  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end
  
end
